# Test using rust

language: rust

services: docker

branches:
    only:
      - master

# Install tools for running tets
  install:
    - cargo install cross

# Setup Jobs per platform
jobs:
    include:
      #64-Bit Tests
      - &test
        stage: test
        script: cross test --target $TARGET
        env: TARGET=x86_64-unkown-linux-gnu
      #32-Bit Tests
      - <<: *test
        env: TARGET=i686-unknown-linux-gnu
      #64-Bit Release
      - &deploy
        stage: deploy
        env: TARGET=x86_64-unknown-linux-gnu
        script: skip
        before_deploy:
          -cross build --release --target $TARGET
          - cp target/$TARGET/release/travis-docker-demo .
          - tar czf travis-docker-demo-$TARGET-TRAVIS_BUILD_NUMBER.tar.gz travis-docker-demo
          - TRAVIS_TAG=build-$TRAVIS_BUILD_NUMBER
        deploy:
          api_key: $GITHUB_TOKEN
          file: travis-docker-demo-$TARGET-$TRAVIS_BUILD_NUMBER.tar.gz
          provider: releases
          skip_cleanup: true
          # 32-bit release
          - <<: *deploy
            env: TARGET=i686-unknown-linux-gnu
